pulp/oci_env

.github/workflows/ci.yaml, client/oci_env/commands.py
```
dnewswan-mac:oci_env dnewswan$ oci-env db reset
You have requested a database reset.
This will IRREVERSIBLY DESTROY
ALL data in the database "pulp".
Are you sure you want to do this?
Type 'yes' to continue, or 'no' to cancel: pulp [None]: root:INFO: Executing... "DROP DATABASE "pulp";"
pulp [None]: root:INFO: Executing... "CREATE DATABASE "pulp" WITH OWNER = "postgres"  ENCODING = 'UTF8';"
Reset successful.
Restarting oci_env_pulp_1  ... done
Restarting oci_env__base_1 ... done
Waiting for API to restart (attempt 1 of 10)
Waiting for API to restart (attempt 2 of 10)
Waiting for API to restart (attempt 3 of 10)
Waiting for API to restart (attempt 4 of 10)
Waiting for API to restart (attempt 5 of 10)
Back online
```
=> Wait for compose stack to restart with oci-env db reset

.github/workflows/ci.yaml, client/oci_env/utils.py
```console
$ oci-env compose ps
NAME                COMMAND                  SERVICE             STATUS              PORTS
oci_env-_base-1     "/bin/true"              _base               exited (0)
oci_env-pulp-1      "/init"                  pulp                running             0.0.0.0:5001->5001/tcp, :::5001->5001/tcp
oci_env-ui-1        "docker-entrypoint.s…"   ui                  running             0.0.0.0:8002->8002/tcp, :::8002->8002/tcp
$ oci-env db reset
Error: No such container: oci_env_pulp_1
```
Looks like `docker-compose` names using `-` while `podman-compose` uses `_`
Fixes: #16
=> Fix error when using `oci-env exec` with docker

base/container_scripts/install_unit_requirements.sh
[no-issue]
With the rebuilt `oci_env`, when running unit tests first and without running functional tests before, `pulp_smash` and `pulpcore-client` are missing.
without `pulpcore` in `DEV_SOURCE_PATH`:
```
Traceback (most recent call last):
File "/usr/local/bin/pytest", line 8, in <module>
sys.exit(console_main())
File "/usr/local/lib/python3.8/site-packages/_pytest/config/__init__.py", line 190, in console_main
code = main()
...
File "/usr/local/lib/python3.8/site-packages/_pytest/assertion/rewrite.py", line 168, in exec_module
exec(co, module.__dict__)
File "/usr/local/lib/python3.8/site-packages/pulpcore/tests/functional/__init__.py", line 5, in <module>
from pulp_smash.config import get_config
ModuleNotFoundError: No module named 'pulp_smash'
```
`pulpcore` included in …
=> Install `pulp_smash` dependency for unit tests

base/init.sh, client/oci_env/commands.py, client/oci_env/main.py
[noissue]
Fixes API path for `galaxy_base` profile to enable using `pulp cli`.
Support running `pulp cli` with `oci_env` commands: `oci-env pulp <args>` (similar to the pulpcore-manager cmd) 
examples: 
- `oci-env pulp status`
- ` oci-env pulp debug openapi schema`
=> Fix `pulp cli` for galaxy_ng config/profile

.github/workflows/ci.yaml, .gitignore, base/container_scripts/db_restore.sh, base/container_scripts/db_snapshot.sh, client/oci_env/commands.py, client/oci_env/main.py
Add db snapshot and db restore commands to snapshot and restore postgres and /var/lib/pulp/.
```
oci-env db -h
usage: oci-env db [-h] [-f FILENAME] {reset,snapshot,restore}
positional arguments:
{reset,snapshot,restore}
optional arguments:
-h, --help            show this help message and exit
-f FILENAME           Back up or restore the database and artifacts to a file in OCI_ENV_PATH/db_back/
```
=> Add db snapshot and restore commands.

.github/workflows/ci.yaml
The Mac OS CI has been super slow and unreliable to the point where it's becoming more of a deterrent than useful.
=> Disable mac CI

base/container_scripts/install_performance_requirements.sh, base/container_scripts/run_performance_tests.sh, client/oci_env/main.py
See pulp_rpm/tests/performance, for example.
Will install perfest_requirements if found, defaulting to functest_requirements if not.
closes #106
=> Taught oci_env about the possible existence of 'performance' tests.

.github/workflows/ci.yaml, client/oci_env/logger.py, client/oci_env/utils.py, client/setup.py
Forgetting to set OCI_ENV_PATH or not setting it correctly is a pain point with using oci-env.
=> Enumerate the OCI_ENV_PATH automatically.

client/oci_env/commands.py, client/oci_env/main.py, client/oci_env/utils.py
1) allow environment overrides in config
If I want to use multiple checkouts for my oci stack, I'd have to alter DEV_SOURCE_PATH within on of the files inside the profile. For quickly switching back and forth between those checkouts and the public pip installed packages or when trying to debug things, having to edit or find the right spot in the profile gets annoying. With this patch, we can instead do something like ...
```
DEV_SOURCE_PATH=pulpcore:pulp_ansible:galaxy_ng oci-env compose build
```
This is especially useful in galaxy_ng now that we have an "actionlib" wrapping around oci-env where most devs don't even know what all the moving parts are or where the relevant files reside.
2) more debug logging
oci-env does a lot of "magic" and it's mostly hidden from the user. We need it to …
=> Allow environment overrides in config and add more debug logging.

base/container_scripts/install_client.sh, base/container_scripts/install_functional_requirements.sh, base/dev_requirements.txt
[noissue]
Python packages get installed in different repositories. pip installs repositories to Python 3.8 repository, while pip3 installs to Python 3.11.
When running `oci-env generate-client -i` or `oci-env test -i -p pulp_ansible functional`, requirements and packages are installed in different repositories and don't see each other.
```
[root@457fa361fd99 /]# pip list | grep pulp
pulp-ansible-client 0.19.0.dev0 /src/pulp-openapi-generator/pulp_ansible-client
pulp-cli            0.20.2
pulp-cli-deb        0.0.4
pulp-glue           0.20.2
pulpcore-client     3.30.0.dev0 /src/pulp-openapi-generator/pulpcore-client
```
```
[root@457fa361fd99 /]# pip3 list | grep pulp
pulp-ansible                             0.19.0.dev0 /src/pulp_ansible
pulp-container                           2.16.0 …
```
=> Use pip3 for `install_client.sh` and `functest_requirements.txt`

base/Dockerfile
This reverts commit 07ef2e28d371c970f8a8b4afb9f718ea966d574f.
It is no longer required to install `which` here because it is installed in the [base image](https://github.com/pulp/pulp-oci-images/blob/latest/images/Containerfile.core.base#L65)
I am running oci_env in CI environment and came across this when trying to improve build times it saves me 40s
=> Revert "Adds the `which` utility needed by some tests."

base/Dockerfile
```
oci-env compose build --build-arg BASE_IMAGE=foo
```
I am running oci env inside an CI environment and o not want to run into rate limiting
backwards compatibility is kept by setting default value.
=> Add possibility to overwrite base image

staging_docs/dev/guides/create-custom-profiles.md, staging_docs/dev/guides/create-multiple-envs.md, staging_docs/dev/guides/run-tests.md, staging_docs/dev/guides/troubleshooting/macos_troubleshooting_tips.md, staging_docs/dev/index.md, staging_docs/dev/learn/how-it-works.md, staging_docs/dev/reference/profile-config.md, staging_docs/dev/reference/profiles/galaxy_base.md, staging_docs/dev/reference/profiles/galaxy_ui.md, staging_docs/dev/reference/profiles/local_fixtures.md, staging_docs/dev/reference/profiles/opentelemetry_dev.md, staging_docs/dev/reference/profiles/pminio.md, staging_docs/dev/reference/profiles/pulp_ansible_base.md, staging_docs/dev/reference/profiles/pulp_container_base.md, staging_docs/dev/reference/profiles/pulp_rpm_base.md, staging_docs/dev/tutorials/quickstart.md
What this does:
- Creates the placeholder structure for the new docs
- Split content from README.md into staging docs
- Changes some parts and titles to fit better
- Copy Profiles READMES to reference
- They look nice where they are. Maybe repos can provide a pre-hook script to `pulp-docs` that will do plugin-specific stuff on serve/build time. In this case, copying those profiles to reference section.
- Remove `docs/` folder. It wasn't being served and had only one file, which lives now in staging docs.
=> Migrate to new docs stack

base/Dockerfile, base/switch_python
With the oci_env now using the new centos9 images, the default python version is now 3.9. 
*Note* We can now publish other python version oci-images, but we haven't done so yet.
=> Update switch_python script to new default python version 3.9

README.md, staging_docs/dev/guides/create-multiple-envs.md
The documentation did not mention that for running multiple Pulp instances, each instance must have not only different API_PORT and COMPOSE_PROJECT_NAME, but also different DOCS_PORT. This commit adds this information to the documentation and README.
[noissue]
=> Docs fix - multiple Pulp instances

.github/workflows/ci.yaml
Github action workers are coming up sporadically without a docker-compose command. This could be due to a newer ubuntu that has finally deprecated the package, but i'm not exactly sure. In either case, this throws the upstream binary into /usr/local/bin so that it doesn't collide with anything in /usr/bin
NOTE:
Test failures are due to pulpcli dep issues per https://issues.redhat.com/browse/AAH-3335
=> always install docker-compose for the ubuntu integration tests

base/Dockerfile, base/container_scripts/get_dynaconf_var.sh
These two issues are causing all galaxy oci-env based CI to fail polling checks.
1. One of our dependencies is emitting error messages to stderr when dynaconf runs, and the oci script is capturing that within the values it it trying to get. This shows up when the stack tries to get the API_ROOT from dynaconf and includes a bunch of errors in the result, then the poll fails because it's adding a bunch of junk to the url.
2. When the stack comes up, it tries to build translations which are dependant on gettext
=> Ignore dynaconf stderr and install gettext

.github/workflows/ci.yaml, .github/workflows/docs-ci.yml
This PR updates GH workflows to use the latest versions of actions and Python 3.11. See https://github.com/actions/runner-images/issues/11101 and https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/ for more details.
=> Update CI to use the latest actions

README.md, staging_docs/dev/tutorials/quickstart.md
This PR fixes a few issues that were overlooked in #178:
- The link in `README.md` was updated to use a relative path, as GitHub does not recognize the `site:` link scheme
- Minor formatting issues and typos in the `quickstart` documentation were corrected
=> Fix link in README and minor quickstart doc issues

base/Dockerfile, base/switch_python
To refresh your env this should be enough:
```bash
oci-env compose build
oci-env compose up --force-recreate
```
If not let a comment here with what worked for you.
=> Update python version to match the new lowerbound python
