README.md

Fixes typo in the readme.

---

.github/workflows/ci.yaml
README.md
client/oci_env/commands.py
client/oci_env/main.py
client/oci_env/templates.py
client/oci_env/utils.py
profiles/galaxy_base/README.md
profiles/galaxy_ui/README.md
profiles/galaxy_ui/profile_requirements.txt
profiles/pulp_ansible_base/README.md

* Add new commands:
* generate a profile:`oci-env profile init -p PLUGIN_NAME PROFILE_NAME`.
* list available profiles: `oci-env profile ls`
* show profile docs: `oci-env profile docs`
* Add READMEs to profiles.
* Add profile_requirements.txt to allow profiles to declare other profiles that are required for them to function.

Add init-profile command.

---

base/container_scripts/configure_pulp_smash.sh
base/container_scripts/database_reset.sh
base/container_scripts/get_dynaconf_var.sh
base/container_scripts/install_client.sh
base/container_scripts/install_functional_requirements.sh
base/container_scripts/install_lint_requirements.sh
base/container_scripts/install_unit_requirements.sh
base/container_scripts/run_functional_tests.sh
base/container_scripts/run_lint_tests.sh
base/container_scripts/run_unit_tests.sh

Fixed some more shellcheck complaints.

Don't use deprecated {e,f}grep

---

.github/workflows/ci.yaml

Adding mac CI

---

base/local_scripts/generate_client.sh

fixes: #51
Requires https://github.com/pulp/pulp-openapi-generator/pull/79

Fix generate-client on docker w/ selinux

---

base/compose.yaml
base/dev_requirements.txt

Add py-spy to dev tools

---

base/container_scripts/run_functional_tests.sh
base/container_scripts/run_unit_tests.sh
base/init.sh

Runs tests as user pulp

---

base/container_scripts/run_functional_tests.sh

No-Issue
Signed-off-by: James Tanner <tanner.jc@gmail.com>

Check for functional test necessities and throw helpful errors if missing

---

README.md

Fix a path to pulp services

---

profiles/pulp_container_base/README.md
profiles/pulp_container_base/pulp_config.env

Add a profile that configures a token server for pulp_container

---

base/Dockerfile

Set the XDG_CONFIG_HOME variable needed for some shell operations

---

base/init.sh

Fixes the command used to add the pulp user to the wheel group.

---

base/container_scripts/db_restore.sh
base/container_scripts/db_snapshot.sh
client/oci_env/commands.py
client/oci_env/main.py

Include certs in backup so that encrypted fields in the database don't get corrupted.

Include certs in backup and restore

---

README.md

[noissue]
I would have found this example useful. Could be extended by another example using curl.

Add an authenticated API example

---

base/dev_requirements.txt

Add pulp-cli-deb to dev requirements

---

base/Dockerfile

Adds the which utility needed by some tests

---

client/oci_env/commands.py
client/oci_env/main.py
client/oci_env/utils.py

This allows us to run podman pull/push commands inside the container. Also, the change is required to run pulp_container tests in general.
[noissue]

Use the privileged mode to exec on the container

---

profiles/pminio/README.md

Add a note about /etc/hosts/ aliases for pminio

---

client/oci_env/commands.py

Generate bindings based on the plugin name

---

.github/workflows/ci.yaml
base/container_scripts/db_restore.sh
client/oci_env/utils.py

unblocks https://github.com/ansible/galaxy_ng/pull/1730

wait for s6 to get locks and emit container logs when polling fails.

---

client/oci_env/utils.py

fix f-string

---

profiles/opentelemetry_dev/README.md

Mention that otel profile cannot be used with other profiles

---

client/oci_env/commands.py
client/oci_env/main.py
client/oci_env/utils.py

* some flake8 errors
* unused import of [deprecated distutils](https://docs.python.org/3.10/library/distutils.html) package raising errors in python12

Fix some python problems and errors

---

.github/workflows/ci.yaml
base/container_scripts/install_functional_requirements.sh
base/container_scripts/install_lint_requirements.sh
base/container_scripts/install_performance_requirements.sh
base/container_scripts/install_unit_requirements.sh
base/container_scripts/run_functional_tests.sh
base/container_scripts/run_lint_tests.sh
base/container_scripts/run_performance_tests.sh
base/container_scripts/run_unit_tests.sh

- Disable 'podman' in the TEST matrix.
- Update the oci-env to be compatible with the pulp_file merge.

Disable "podman" in the TEST matrix and update oci-env to be compatible with the pulp_file merge

---

base/dev_requirements.txt

Get the latest pulp-cli version installed

---

base/container_scripts/get_dynaconf_var.sh

Switch get_dynaconf_var to use `dynaconf get`

---

base/utils.sh

Based on this new feature being added to the ci-centos image: https://github.com/pulp/pulp-oci-images/pull/623

Add correct logic for new templated nginx file

---

profiles/opentelemetry_dev/compose.yaml

Expose the port for prometheus

---

.github/workflows/ci.yaml
.github/workflows/docs-ci.yml
Makefile
doc_requirements.txt

Related to: https://github.com/pulp/pulp-docs/issues/31
[noissue]

Add unified docs-ci

---

.github/workflows/ci.yaml
profiles/pulp_ui/README.md
profiles/pulp_ui/compose.yaml
profiles/pulp_ui/profile_default_config.env

Requires the dockerfile in https://github.com/pulp/pulp-ui/pull/70

Add profile for new pulp-ui

---

profiles/pulp_ui/compose.yaml

With https://github.com/pulp/pulp-ui/pull/111 the dev env needs this new value.

Add new config value for ui-profile

---

base/utils.sh

Includes debugging stmts, and is a very ugly Big Hammer - there's prob a better/more-elegant sed

Fix to recognize the ipv6-enablement now in nginx.conf.j2.
